name: My Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    - name: Install php
      run: sudo apt-get update && sudo apt-get install -y php
    - name: Install mysql
      run: sudo apt-get update && sudo apt-get install -y mysql-server
